/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcexample.h"

bool_t
xdr_add_in (XDR *xdrs, add_in *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->left))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->right))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_add_out (XDR *xdrs, add_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_square_in (XDR *xdrs, square_in *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_square_out (XDR *xdrs, square_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}
