/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCEXAMPLE_H_RPCGEN
#define _RPCEXAMPLE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct add_in {
	int left;
	int right;
};
typedef struct add_in add_in;

struct add_out {
	int value;
};
typedef struct add_out add_out;

struct square_in {
	int value;
};
typedef struct square_in square_in;

struct square_out {
	int value;
};
typedef struct square_out square_out;

#define RPCEXAMPLE_PROG 0x53778894
#define RPCEXAMPLE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDPROC 1
extern  add_out * addproc_1(add_in *, CLIENT *);
extern  add_out * addproc_1_svc(add_in *, struct svc_req *);
#define SQUAREPROC 2
extern  square_out * squareproc_1(square_in *, CLIENT *);
extern  square_out * squareproc_1_svc(square_in *, struct svc_req *);
extern int rpcexample_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDPROC 1
extern  add_out * addproc_1();
extern  add_out * addproc_1_svc();
#define SQUAREPROC 2
extern  square_out * squareproc_1();
extern  square_out * squareproc_1_svc();
extern int rpcexample_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_add_in (XDR *, add_in*);
extern  bool_t xdr_add_out (XDR *, add_out*);
extern  bool_t xdr_square_in (XDR *, square_in*);
extern  bool_t xdr_square_out (XDR *, square_out*);

#else /* K&R C */
extern bool_t xdr_add_in ();
extern bool_t xdr_add_out ();
extern bool_t xdr_square_in ();
extern bool_t xdr_square_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCEXAMPLE_H_RPCGEN */
